/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evaluación;

import com.mysql.jdbc.MysqlIO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author johans
 */
public class ObtieneInfo  extends JFrame implements ActionListener{

    /**
     * Creates new form ObtieneInfo
     *
     * @throws java.io.IOException
     */
    public ObtieneInfo() {       

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LISTAR__ = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LISTAR__.setText("Listar");
        LISTAR__.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTAR__ActionPerformed(evt);
            }
        });

        jButton2.setText("Consultar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LISTAR__)
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LISTAR__)
                    .addComponent(jButton2))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LISTAR__ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTAR__ActionPerformed
        try {
            // Se registra el Driver de MySQL       
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            // Se crea un Statement, para realizar la consulta
            try ( // Se obtiene una conexión con la base de datos. Hay que
            // cambiar el usuario "root" y la clave "la_clave" por las
            // adecuadas a la base de datos que estemos usando.
                    Connection conexion = DriverManager.getConnection(
                            "jdbc:mysql://localhost/admin", "johans", "")) {
                // Se crea un Statement, para realizar la consulta
                Statement s = conexion.createStatement();
                // Se realiza la consulta. Los resultados se guardan en el
                // ResultSet rs
                ResultSet rs = s.executeQuery("select * from user");
                // Se recorre el ResultSet, mostrando por pantalla los resultados.
                while (rs.next()) {
                    /*System.out.println(rs.getInt("Id") + " " + rs.getString(2)
                            + " " + rs.getDate(3));*/
                    System.out.println(rs.getInt("Id"));
                }
                // Se cierra la conexión con la base de datos.
            }
        } catch (SQLException e) {
            System.out.println(e.getSQLState());
        }
    }//GEN-LAST:event_LISTAR__ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObtieneInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ObtieneInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LISTAR__;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
